/* eslint-disable @next/next/no-img-element */
// About.tsx

import type { NextPage } from "next";
import Head from "next/head";
import PageTitle from "../components/PageTitle"; // import the interface
import { AboutProps } from "../properties/props";

const About: NextPage<AboutProps> = ({
  title,
  firstContent,
  secondContent,
  thirdContent,
  firstImage,
  secondImage,
  secondTitle,
  fourthContent,
  fifthContent,
  author,
}) => {
  return (
    <>
      <Head>
        <title>Store - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={title} />

      <section className="bg0 p-t-75 p-b-120">
        <div className="container">
          <div className="row p-b-148">
            <div className="col-md-7 col-lg-8">
              <div className="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
                <h3 className="mtext-111 cl2 p-b-16">{title}</h3>
                <p className="stext-113 cl6 p-b-26">{firstContent}</p>
                <p className="stext-113 cl6 p-b-26">{secondContent}</p>
                <p className="stext-113 cl6 p-b-26">{thirdContent}</p>
              </div>
            </div>

            <div className="col-11 col-md-5 col-lg-4 m-lr-auto">
              <div className="how-bor1 ">
                <div className="hov-img0">
                  <img src={firstImage} alt="IMG" />
                </div>
              </div>
            </div>
          </div>

          <div className="row">
            <div className="order-md-2 col-md-7 col-lg-8 p-b-30">
              <div className="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
                <h3 className="mtext-111 cl2 p-b-16">{secondTitle}</h3>
                <p className="stext-113 cl6 p-b-26">{fourthContent}</p>
                <div className="bor16 p-l-29 p-b-9 m-t-22">
                  <p className="stext-114 cl6 p-r-40 p-b-11">{fifthContent}</p>
                  <span className="stext-111 cl8">{author}</span>
                </div>
              </div>
            </div>

            <div className="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
              <div className="how-bor2">
                <div className="hov-img0">
                  <img src={secondImage} alt="IMG" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export async function getStaticProps() {
  const response = await fetch("http://localhost:5001/about_page");
  const data = await response.json();
  console.log(data);

  const {
    title,
    first_content,
    second_content,
    third_content,
    first_image,
    second_image,
    second_title,
    fourth_content,
    fifth_content,
    author,
  } = data;

  return {
    props: {
      title,
      firstContent: first_content,
      secondContent: second_content,
      thirdContent: third_content,
      firstImage: first_image,
      secondImage: second_image,
      secondTitle: second_title,
      fourthContent: fourth_content,
      fifthContent: fifth_content,
      author,
    },
  };
}

export default About;
