import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { HomeProps } from "../properties/props";

const Home: NextPage<HomeProps> = ({ bannerData, productsData, blogsData  }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner bannerData={bannerData} />
      <CategoryPicker />
      <FeaturedProducts productsData={productsData} />
      <FeaturedBlogs blogsData={blogsData} />
    </>
  );
};

export const getStaticProps = async () => {
  const bannerRes = await fetch("http://localhost:5001/banner_content");
  const bannerData = await bannerRes.json();

  const productRes = await fetch("http://localhost:5001/products/?_limit=4");
  const productsData = await productRes.json();

  const blogRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const blogsData = await blogRes.json();

  return {
    props: {
      bannerData,
      productsData,
      blogsData,
    },
  };
};

export default Home;
